#### A. Математика — круто, но это не точно
Давайте вспомним начало нашего задачника, когда всё было просто: мы не использовали ни циклы, ни коллекции, ни объектно-ориентированное программирование. Перед нами были только входные данные и требовалось предоставить результат.

Напишите программу, которая вычисляет значение функции:

�
(
�
)
=
log
⁡
32
�
3
16
+
�
cos
⁡
�
⋅
�
2
⋅
�
−
sin
⁡
2
�
�
f(x)=log 
32
​
 x 
16
3
​
 
 +x 
cos 
2⋅e
π⋅x
​
 
 −sin 
2
  
π
x
​
 
Формат ввода
Вводится действительное число 
�
x

Формат вывода
Одно число — значение функции в заданной точке.

Пример 1
Ввод
2.71
Вывод
0.4818035253577275
Пример 2
Ввод
12.345
Вывод
4.880549344757598


In [ ]:
import math


x = float(input())

y = math.log(math.pow(x, 3 / 16), 32) + math.pow(x, math.cos(math.pi * x / 2 / math.e))\
    - math.pow(math.sin(x / math.pi), 2)
print(y)

#### B. Потоковый НОД (тест 1 -- Ошибка во время исполнения (RE))
Напишите программу, находящую наибольшие общие делители для всех переданных в стандартный поток последовательностей чисел.

Формат ввода
Вводятся строки чисел, разделённых пробелами.

Формат вывода
Последовательность чисел — наибольшие общие делители всех последовательностей.

Пример
Ввод
2 1000 20 34
36 12
3 96 12
6
7 8 9 10
Вывод
2
12
3
6
1


In [ ]:
from sys import stdin
import math

gcd = []
for line in stdin:
    numbers = [int(i) for i in line.split()]
    gcd.append(math.gcd(numbers))

for item in gcd:
    print(item)
    

#### C. Есть варианты? (тест 7 -- Ответ неверен (WA))
Вася пришёл на образовательный семинар и обнаружил, что зрителей на мероприятии — 
�
N, а количество мест — 
�
M.
Помогите Васе определить вероятность того, что он попадёт на семинар.

Формат ввода
Два числа 
�
N и 
�
M.

Формат вывода
Два числа — количество вариантов, в которых Вася попадает на семинар и количество всех вариантов групп на семинаре.

Примечание
В первом примере обозначим участников числами 1, 2, 3, 4. Предположим, что 1 — это Вася.

Тогда все вариации участников выглядят так:

1 2
1 3
1 4
2 3
2 4
3 4
А благополучными из них для Васи являются только 3:

1 2
1 3
1 4
Пример 1
Ввод
4 2
Вывод
3 6
Пример 2
Ввод
10 3
Вывод
36 120


In [ ]:
import math


n, m = [int(i) for i in input().split()]
variants = math.comb(n, m)
if m <= n:
    probability = m / n
    print(int(probability * variants), variants)
else:
    print(1, 1)


#### D. Среднее не арифметическое
Средним геометрическим нескольких положительных вещественных чисел называют такое число, которым можно заменить каждое из этих чисел так, чтобы их произведение не изменилось.

Формула среднего геометрического для 
�
n чисел выглядит так:

�
(
�
1
,
�
2
,
.
.
.
,
�
�
)
=
�
1
⋅
�
2
⋅
⋅
⋅
�
�
�
=
(
∏
�
=
1
�
�
�
)
1
�
G(x 
1
​
 ,x 
2
​
 ,...,x 
n
​
 )= 
n
  
x 
1
​
 ⋅x 
2
​
 ⋅⋅⋅x 
n
​
 
​
 =(∏ 
i=1
n
​
 x 
i
​
 ) 
n
1
​
 
 
Формат ввода
Вводится последовательность рациональных чисел, разделённых пробелами.

Формат вывода
Одно число — среднее геометрическое переданных чисел.

Пример 1
Ввод
1 2 3 4 5
Вывод
2.605171084697352
Пример 2
Ввод
1.1 1.2 1.3 1.4 1.5
Вывод
1.292252305460076


In [ ]:
import math


lst = [float(i) for i in input().split()]
mult = math.pow(math.prod(lst), 1 / len(lst))
print(mult)

#### E. Шаг навстречу
Два выдуманных человечка Дека и Поля, пользуются каждый своей системой координат. Деке нравится представлять себя в декартовом пространстве, а Поле — в полярном.

Напишите программу, определяющую кротчайшее расстояние, которое нужно пройти Деке и Поле, чтобы встретиться.

Формат ввода
В первой строке записаны координаты Деки: два рациональных числа — 
�
x и 
�
y
Во второй строке записаны координаты Поли: два рациональных числа — 
�
ρ и 
�
ϕ

Формат вывода
Одно число — расстояние между Декой и Полей.

Примечание
Дека и Поля живут на одной плоскости с общим центром.

�
ϕ — измеряется в радианах.

Пример 1
Ввод
-7 20
7 3.141592653589793
Вывод
20.0
Пример 2
Ввод
10 10
10.142135623730951 0.7853981633974483
Вывод
3.9999999999999996


In [ ]:
import math


deca = [float(i) for i in input().split()]
poly = [float(i) for i in input().split()]

poly_deca = poly[0] * math.cos(poly[1]), poly[0] * math.sin(poly[1])
print(math.dist(deca, poly_deca))

#### F. Матрица умножения
Напишите функцию multiplication_matrix, которая принимает размер матрицы (
�
N) и возвращает массив описывающий таблицу умножения 
�
N на 
�
N.

Примечание
Ваше решение должно содержать только функции.
В решении не должно быть вызовов требуемых функций.

Пример 1
Ввод
print(multiplication_matrix(3))
Вывод
[[1 2 3]
 [2 4 6]
 [3 6 9]]
Пример 2
Ввод
print(multiplication_matrix(5))
Вывод
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [ ]:
import numpy as np


def multiplication_matrix(n):
    a = np.arange(1, n + 1)
    b = a.reshape(n, 1)
    c = b * a
    return c

#### G. Шахматная подготовка
Представьте, что вы пишете компьютерную игру «Шахматы». Вам надо смоделировать шахматную доску, которая представляет собой матрицу. Чёрная клетка представляется нулём, а белая — единицей. Если смотреть на доску сверху, то левая верхняя клетка — белая.

Напишите функцию make_board, которая принимает размер шахматной доски, и возвращает матрицу, моделирующую заданную доску.

Установите тип элементов матрицы int8.

Примечание
Ваше решение должно содержать только функции.
В решении не должно быть вызовов требуемых функций.

Пример 1
Ввод
print(make_board(4))
Вывод
[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]
Пример 2
Ввод
print(make_board(6))
Вывод
[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


In [ ]:
import numpy as np


def make_board(n):
    board = np.zeros((n, n), dtype="int8")
    for i in range(n):
        for j in range(n):
            if not (i + j) % 2:
                board[i][j] = 1
    
    return board

#### H. Числовая змейка 3.0
Когда-то вы помогали детсадовцам с различными змейками. Давайте реализуем её на основе массивов.

Напишите функцию snake, которая принимает ширину (
�
M) и высоту (
�
N) змейки, а также именованный параметр direction.

Параметр direction могут принимать значения:

H — горизонтальная змейка, используется по умолчанию;
V — вертикальная змейка.
Функция должна вернуть матрицу, представляющую змейку, с ячейками типа int16.

Примечание
Ваше решение должно содержать только функции.
В решении не должно быть вызовов требуемых функций.

Пример 1
Ввод
print(snake(5, 3))
Вывод
[[ 1  2  3  4  5]
 [10  9  8  7  6]
 [11 12 13 14 15]]
Пример 2
Ввод
print(snake(5, 3, direction='V'))
Вывод
[[ 1  6  7 12 13]
 [ 2  5  8 11 14]
 [ 3  4  9 10 15]]


In [ ]:
import numpy as np


def snake(a, b, direction='H'):
    c = 0
    if direction == 'V':
        c = b
        b = a
        a = c
    board = np.zeros((b, a), dtype="int16")
    for i in range(b):
        for j in range(a):
            if not i % 2:
                board[i][j] = j + 1 + i * a
            else:
                board[i][j] = (i + 1) * a - j
    if direction == 'V':
        board = board.transpose()
    return board

#### I. Вращение
Напишите функцию rotate, принимающую двумерную матрицу и один из углов поворота: 
90
°
90°, 
180
°
180°, 
270
°
270° и 
360
°
360°.

Функция должна вернуть новую матрицу соответствующую заданному повороту по часовой стрелке.

Примечание
Ваше решение должно содержать только функции.
В решении не должно быть вызовов требуемых функций.

Пример 1
Ввод
print(rotate(np.arange(12).reshape(3, 4), 90))
Вывод
[[ 8  4  0]
 [ 9  5  1]
 [10  6  2]
 [11  7  3]]
Пример 2
Ввод
print(rotate(np.arange(12).reshape(3, 4), 270))
Вывод
[[ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]
 [ 0  4  8]]


In [ ]:
import numpy as np


def rotate(matrix, angle):
    if angle == 360:
        return matrix
    if angle == 90:
        return np.rot90(matrix, -1)
    if angle == 180:
        return np.rot90(np.rot90(matrix))
    if angle == 270:
        return np.rot90(matrix)

#### J. Лесенка
Напишите функцию stairs, принимающую вектор и возвращающую матрицу, в которой каждая строка является копией вектора со смещением.

Примечание
Ваше решение должно содержать только функции.
В решении не должно быть вызовов требуемых функций.

Пример 1
Ввод
print(stairs(np.arange(3)))
Вывод
[[0 1 2]
 [2 0 1]
 [1 2 0]]
Пример 2
Ввод
print(stairs(np.arange(5)))
Вывод
[[0 1 2 3 4]
 [4 0 1 2 3]
 [3 4 0 1 2]
 [2 3 4 0 1]
 [1 2 3 4 0]]


In [ ]:
import numpy as np


def stairs(vect):
    length = np.size(vect)
    matrix = np.zeros((length, length), dtype="int16")
    for i in range(length):
        for j in range(length):
            matrix[i][j] = vect[j - i % length]
    return matrix